apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: spectra-prometheus
  namespace: monitoring
spec:
  replicas: 2
  serviceAccountName: prometheus
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceMonitorSelector:
    matchLabels:
      team: spectra
  resources:
    requests:
      memory: 400Mi
      cpu: 200m
    limits:
      memory: 1Gi
      cpu: 500m
  storage:
    volumeClaimTemplate:
      spec:
        storageClassName: standard
        resources:
          requests:
            storage: 10Gi
  alerting:
    alertmanagers:
      - namespace: monitoring
        name: alertmanager
        port: web
