version: '3.8'

services:
  api:
    build:
      context: ../../
      dockerfile: docker/service/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/spectra
    depends_on:
      - db
    volumes:
      - ../../:/app
      - /app/node_modules

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=spectra
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
