name: development
on: 
  workflow_dispatch:
environment:
  name: development
  url: https://dev.spectra.ai

env:
  AWS_REGION: us-west-2
  ENVIRONMENT: development
  KUBERNETES_NAMESPACE: spectra-development
