name: Shared Workflow Configuration

env:
  AWS_REGION: us-west-2
  REGISTRY: docker.io
  ORGANIZATION: spectra

# Reusable job configurations
jobs:
  aws-auth:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

  docker-auth:
    name: Configure Docker Credentials
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  notify-repos:
    name: Notify Dependent Repositories
    runs-on: ubuntu-latest
    needs: [deploy]
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deployment-complete
          client-payload: |
            {
              "environment": "${{ github.event.inputs.environment }}",
              "status": "success"
            }
