name: Shared Workflows

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (development/staging/production)'
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true
      GITHUB_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions
          aws-region: us-west-2

  docker-auth:
    name: Configure Docker Credentials
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  notify-repos:
    name: Notify Dependent Repositories
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: deployment-complete
          client-payload: |
            {
              "environment": "${{ inputs.environment }}",
              "status": "success"
            }
