on:


# Shared reusable workflow for Spectra infra
# Usage: Call this workflow with required secrets and environment input.

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: 'Environment (development/staging/production)'
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_TOKEN:
        required: true

permissions:
  id-token: write
  contents: read

jobs:
  aws-auth:
    name: Configure AWS Credentials
    runs-on: ubuntu-latest
    steps:

      # Assumes OIDC role is configured in AWS for this repo.
      # Assumes OIDC role is configured in AWS for this repo.
      - uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::<YOUR_ACCOUNT_ID>:role/github-actions  # <-- Replace with your actual AWS role ARN
          aws-region: us-west-2

  docker-auth:
    name: Configure Docker Credentials
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          registry: docker.io
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

  notify-repos:
    name: Notify Dependent Repositories
    runs-on: ubuntu-latest
    steps:
      - uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          event-type: deployment-complete
          client-payload: |
            {
              "environment": "${{ inputs.environment }}",
              "status": "success"
            }
