name: Deploy to Railway

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'staging'
        type: choice
        options:
          - development
          - staging
          - production

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Railway CLI
      run: npm install -g @railway/cli
      
    - name: Configure Railway Project
      run: |
        railway link --environment ${{ github.event.inputs.environment || 'staging' }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
    - name: Deploy to Railway
      run: |
        railway up --environment ${{ github.event.inputs.environment || 'staging' }}
      env:
        RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
